---
- name: Download .tar.gz Node-exporter file
  delegate_to: 127.0.0.1
  run_once: True
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: "./roles/exporter/files/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    mode: 0755
    timeout: 60
    force: true
    validate_certs: false
- name: Add {{node_exporter_user}} user
  become: true
  become_method: sudo
  become_user: root
  user:
    name: "{{node_exporter_user}}"
    shell: /usr/sbin/nologin
    system: true
    create_home: false
- name: Upload .tar.gz Node-exporter file to instance
  copy:
    src: "./roles/exporter/files/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
  register: download_node_exporter_binaries
  until: download_node_exporter_binaries is succeeded
- name: Create Node-exporter directtory
  become: true
  become_method: sudo
  become_user: root
  file:
    state: directory
    path: "{{ node_exporter_dir }}"
    mode: 0770
    owner: "{{ node_exporter_user }}"
- name: Extract Node-exporter in the installation directory
  become: true
  become_user: root
  become_method: sudo
  unarchive:
    copy: false
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: "{{ node_exporter_dir }}"
    extra_opts: [--strip-components=1]
    creates: "/opt/node-exporter/node-exporter"
- name: Create init file
  become: true
  become_user: root
  become_method: sudo
  template:
    src: node-exporter.service.j2
    mode: 0755
    owner: root
    dest: /etc/systemd/system/node-exporter.service
  notify: restart Node-exporter
