---
all:
  hosts:
    prometheus-server-debian01:
      ansible_host: 192.168.1.2
    grafana-debian01:
      ansible_host: 192.168.1.3
    node-exporter-debian01:
      ansible_host: 192.168.1.4
  vars:
    ansible_connection: ssh
    ansible_user: <ansible_user>
    control_node_user: <control_node_user>

prometheus-server:
  hosts:
    prometheus-server-debian01:
grafana:
  hosts:
    grafana-debian01:
node-exporter:
  hosts:
    node-exporter-debian01:
