---
- name: Download .deb Grafana file
  delegate_to: 127.0.0.1
  run_once: True
  get_url:
    url: "https://dl.grafana.com/enterprise/release/grafana-enterprise_{{ grafana_version }}_amd64.deb"
    dest: "./roles/grafana/files/grafana-enterprise_{{ grafana_version }}_amd64.deb"
    mode: 0755
    timeout: 60
    force: true
    validate_certs: false
    force: false
- name: Upload .deb Grafana file to instance
  copy:
    src: "./roles/grafana/files/grafana-enterprise_{{ grafana_version }}_amd64.deb"
    dest: "/tmp/grafana-enterprise_{{ grafana_version }}_amd64.deb"
  register: download_grafana_binaries
  until: download_grafana_binaries is succeeded
- name: Install Grafana
  become: true
  apt:
    deb: "/tmp/grafana-enterprise_{{ grafana_version }}_amd64.deb"
    state: present
  notify: restart Grafana
