---
- name: Install Node-exporter
  hosts: node-exporter
  gather_facts: yes
  roles:
    - ./roles/exporter

- name: Install Prometheus
  hosts: prometheus-server
  gather_facts: yes
  roles:
    - ./roles/prometheus

- name: Install Grafana
  hosts: grafana
  gather_facts: yes
  roles:
    - ./roles/grafana
