---
- name: restart Prometheus-server
  become: true
  systemd:
    name: prometheus-server
    state: restarted
    daemon_reload: yes
    enabled: yes
  when: ansible_virtualization_type != 'docker'
